language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"

install: 
    - "$PIP_EXE install coveralls"
    - "$PIP_EXE install pyyaml"

script: 
    - "$PYTHON_EXE setup.py install"
    - "ck pull repo:ck-web"
    - "coverage run -m tests.test"

after_success: coveralls
