3d-unet-99:
  Offline:
    target_qps: 4.0
  SingleStream:
    target_latency: 400
3d-unet-99.9:
  Offline:
    target_qps: 4.0
  SingleStream:
    target_latency: 400
bert-99:
  Offline:
    target_qps: 4000.0
  Server:
    target_qps: 3800.0
  SingleStream:
    target_latency: 1
bert-99.9:
  Offline:
    target_qps: 2000.0
  Server:
    target_qps: 2000.0
  SingleStream:
    target_latency: 10
resnet50:
  MultiStream:
    target_latency: '432111'
  Offline:
    target_qps: '42959.4'
  Server:
    target_qps: 35000.0
  SingleStream:
    target_latency: '226895'
retinanet:
  MultiStream:
    target_latency: 80
  Offline:
    target_qps: 700.0
  Server:
    target_qps: 650.0
  SingleStream:
    target_latency: 10
