name: Build Python Wheel

on:
  pull_request:
    branches:
      - main
      - dev
      - mlperf-inference

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ['3.9', '3.11', '3.12']
        exclude:
        - os: ubuntu-latest
          python-version: "3.8"

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}


    - name: Build the Python wheel
      run: |
        python3 -m venv cm
        cm\Scripts\activate.bat
        git config --system core.longpaths true
        python3 -m pip install . -v
