name: MLPerf Inference Intel implementations

on:
  schedule:
    - cron: "29 16 * * *" #to be adjusted

jobs:
  build_nvidia:
      if: github.repository_owner == 'gateoverflow'
      runs-on: [ self-hosted, linux, x64, GO-spr ]
      strategy:
        fail-fast: false
        matrix:
          python-version: [ "3.12" ]
          model: [ "resnet50", "bert-99" ]
      steps:
      - name: Test MLPerf Inference Intel ${{ matrix.model }}
        run: |
          if [ -f "gh_action_conda/bin/deactivate" ]; then source gh_action_conda/bin/deactivate; fi
          python3 -m venv gh_action_conda
          source gh_action_conda/bin/activate
          export CM_REPOS=$HOME/GH_CM
          pip install --upgrade cm4mlops
          pip install tabulate
          cm run script --tags=run-mlperf,inference,_all-scenarios,_submission,_full,_r4.1-dev --preprocess_submission=yes --execution_mode=valid  --pull_changes=yes --pull_inference_changes=yes --model=${{ matrix.model }} --submitter="MLCommons" --hw_name=IntelSPR.24c  --implementation=intel    --backend=pytorch    --category=datacenter --division=open --scenario=Offline  --docker_dt=yes --docker_it=no --docker_cm_repo=gateoverflow@cm4mlops --adr.compiler.tags=gcc --device=cpu  --results_dir=$HOME/gh_action_results --submission_dir=$HOME/gh_action_submissions --clean  --docker --quiet
          cm run script --tags=push,github,mlperf,inference,submission --repo_url=https://github.com/gateoverflow/mlperf_inference_unofficial_submissions_v5.0 --repo_branch=main --commit_message="Results from GH action on SPR.24c" --quiet --submission_dir=$HOME/gh_action_submissions --hw_name=IntelSPR.24c
