# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: cm4mlops test

on:
  pull_request:
    branches: [ "main", "dev", "mlperf-inference" ]
    paths:
      - '.github/workflows/test-cm4mlops.yml'
      - 'setup.py'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.12"]
        on: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
          - python-version: "3.7"
            on: "macos-latest"
    runs-on: "${{ matrix.on }}"
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run Test install for cm4mlops
      run: |
        python -m pip install --upgrade pip
        python -m pip install .

