name: Build Python Wheel

on:
  pull_request:
    branches:
      - main
      - dev
      - mlperf-inference
    paths:
      - '.github/workflows/test-cm4mlops-wheel-ubuntu.yml'
      - 'setup.py'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        python-version: ['3.7', '3.8', '3.11', '3.12']
        exclude:
        - os: ubuntu-latest
          python-version: "3.8"

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo apt-get update 
        sudo apt-get install -y python3 python3-pip python3-venv

    - name: Build the Python wheel
      run: |
        python3 -m venv cm
        source cm/bin/activate
        python3 -m pip install . -v
